# Generated by Django 4.1.3 on 2022-11-06 05:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imageupload_fuse',
            fields=[
                ('project', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='fusion_image1')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone', models.BigIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 11, 6, 5, 52, 27, 774271))),
            ],
        ),
        migrations.CreateModel(
            name='Radiologist',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('phone', models.BigIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 11, 6, 5, 52, 27, 775814))),
            ],
        ),
        migrations.CreateModel(
            name='Fusion',
            fields=[
                ('fusion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(default='', max_length=200)),
                ('uploaded_by', models.IntegerField(default=1)),
                ('uploaded_date', models.DateTimeField(default=datetime.datetime(2022, 11, 6, 5, 52, 27, 776523))),
                ('Patient_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PROJECT.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Denoise',
            fields=[
                ('denoise_id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('image_output', models.ImageField(default='', upload_to='ouput')),
                ('uploaded_by', models.IntegerField(default=1)),
                ('uploaded_date', models.DateTimeField(default=datetime.datetime(2022, 11, 6, 5, 52, 27, 775330))),
                ('Patient_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PROJECT.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Classification_Report',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('caption', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='classification')),
                ('tumor_type', models.CharField(default='', max_length=200)),
                ('uploaded_by', models.IntegerField(default=1)),
                ('uploaded_date', models.DateTimeField(default=datetime.datetime(2022, 11, 6, 5, 52, 27, 776130))),
                ('Patient_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PROJECT.patient')),
            ],
        ),
    ]
