# Generated by Django 4.1.3 on 2022-11-06 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fusion',
            name='Patient_name',
        ),
        migrations.DeleteModel(
            name='imageupload_fuse',
        ),
        migrations.AlterField(
            model_name='classification_report',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 5, 59, 57, 329439)),
        ),
        migrations.AlterField(
            model_name='denoise',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 5, 59, 57, 327888)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 5, 59, 57, 327578)),
        ),
        migrations.AlterField(
            model_name='radiologist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 5, 59, 57, 329109)),
        ),
        migrations.DeleteModel(
            name='Fusion',
        ),
    ]
