# Generated by Django 4.1.3 on 2022-11-06 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECT', '0002_remove_fusion_patient_name_delete_imageupload_fuse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('author', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='classification_report',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 6, 5, 55, 398365)),
        ),
        migrations.AlterField(
            model_name='denoise',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 6, 5, 55, 396963)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 6, 5, 55, 396666)),
        ),
        migrations.AlterField(
            model_name='radiologist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 6, 5, 55, 398043)),
        ),
        migrations.CreateModel(
            name='WritingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='classification')),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PROJECT.writing')),
            ],
        ),
    ]
