# Generated by Django 4.1.3 on 2022-11-06 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECT', '0003_writing_alter_classification_report_uploaded_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='classification_report',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 6, 14, 21, 663700)),
        ),
        migrations.AlterField(
            model_name='denoise',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 6, 14, 21, 662095)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 6, 14, 21, 661800)),
        ),
        migrations.AlterField(
            model_name='radiologist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 6, 14, 21, 663330)),
        ),
        migrations.AlterField(
            model_name='writingimage',
            name='writing',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
