# Generated by Django 4.1.3 on 2022-11-15 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECT', '0004_remove_writingimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologist',
            name='newpassword',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='classification_report',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 46, 1, 78235)),
        ),
        migrations.AlterField(
            model_name='denoise',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 46, 1, 77598)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 46, 1, 77353)),
        ),
        migrations.AlterField(
            model_name='radiologist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 46, 1, 77967)),
        ),
        migrations.AlterField(
            model_name='writingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fusion'),
        ),
    ]
