# Generated by Django 4.1.3 on 2022-11-15 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROJECT', '0005_radiologist_newpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification_report',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 11, 45, 492397)),
        ),
        migrations.AlterField(
            model_name='denoise',
            name='uploaded_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 11, 45, 491247)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 11, 45, 490577)),
        ),
        migrations.AlterField(
            model_name='radiologist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 17, 11, 45, 492003)),
        ),
    ]
